#version: "3.8"
#services:
#  workouts_db:
#    image: mysql:8.0.28
#    ports:
#      - "43307:3306"
#    environment:
#      MYSQL_DATABASE: workout
#      MYSQL_ALLOW_EMPTY_PASSWORD: true

version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: workouts     # Nazwa bazy danych
      MYSQL_USER: user         # Nazwa użytkownika
      MYSQL_PASSWORD: user     # Hasło użytkownika
    ports:
      - '3306:3306'                     # Porty hosta:kontenera, na których nasłuchuje MySQL


