server:
  port: 9090
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workouts?sessionVariables=sql_mode=''&serverTimezone=Europe/Warsaw
    username: user
    password: user
  flyway:
    url: jdbc:mysql://localhost:3306/workouts?sessionVariables=sql_mode=''&serverTimezone=Europe/Warsaw
    user: user
    password: user
    locations: classpath:db.migration
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
  mail:
    host: smtp.gmail.com
    port: 587
    username: ???
    password: ???
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    protocol: smtp
    test-connection: false
rsa:
  public-key: 'classpath:\certs\pubic.pem'
  private-key: 'classpath:\certs\private.pem'
app:
  version: ^project.version^



